version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: src/TechChallenge.Api/Dockerfile
    image: techchallenge.api
    ports:
      - 8888:8080
    networks:
      - techchallenge_api_network

  prometheus:
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    image: prometheus-local
    restart: always
    ports: 
      - 9090:9090
    networks:
      - techchallenge_api_network
    volumes: 
      - './prometheus/data:/data'

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: 102030
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    networks:
      - techchallenge_api_network

networks:
  techchallenge_api_network:
    driver: overlay
    attachable: true
