name: .NET Core Desktop

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-latest

    env:
      Solution_Name: TechChallenge.sln
      Test_Project_Path: TechChallenge.Tests\TechChallenge.Tests.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Setup MSBuild.exe
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test $env:Test_Project_Path

    # Generate coverage report using Coverlet
    - name: Generate coverage report
      uses: coverletapp/coverlet@1.3.0
      with:
        target: $env:Test_Project_Path
        output: coverage.cobertura.xml
        format: cobertura

    # Upload coverage report to Codecov
    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v2.1.0
      with:
        token: ${{secrets.CODECOV_TOKEN }}
        file: coverage.cobertura.xml
        flags: unittests
        name: codecov-umbrella

    # Upload coverage report to Coveralls
    - name: Upload coverage report to Coveralls
      uses: coverallsapp/github-action@v1.1.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} 
        path-to-lcov: coverage.cobertura.xml
