name: .NET Core Desktop

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-latest

    env:
      Solution_Name: TechChallenge.sln
      Test_Project_Path: TechChallenge.Tests\TechChallenge.Tests.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Setup MSBuild.exe
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Set up Docker Compose
    - name: Set up Docker Compose
      run: |
        echo "version: '3.8'

        services:
          db:
            image: postgres:latest
            environment:
              POSTGRES_USER: testuser
              POSTGRES_PASSWORD: 102030
              POSTGRES_DB: testdb
            ports:
              - '5432:5432'" > docker-compose.yml

    # Start the database
    - name: Start database
      run: docker-compose up -d

    # Wait for the database to be ready
    - name: Wait for Postgres
      run: |
        echo "Waiting for Postgres to be ready..."
        for i in {1..30}; do
          if docker exec $(docker-compose ps -q db) pg_isready -U testuser -d testdb; then
            echo "Postgres is ready!"
            exit 0
          fi
          echo "Waiting..."
          sleep 2
        done
        echo "Postgres did not become ready in time!"
        exit 1

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test $env:Test_Project_Path

    # Restore the application
    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    # Clean up Docker containers
    - name: Clean up
      if: always()
      run: docker-compose down
